name: "Compatibility"

on:
  workflow_call:

jobs:
  compatibility:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.scan.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: scan
        run: echo "matrix=$(cat .github/distros.json | jq -c .)" >> "$GITHUB_OUTPUT"

  tests:
    needs: compatibility
    name: "${{ matrix.os-name }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.compatibility.outputs.matrix) }}

    container:
      image: ${{ matrix.container }}
      options: --privileged

    steps:
      - name: Install minimal dependencies
        if: ${{ matrix.setup-cmd }}
        run: ${{ matrix.setup-cmd }}

      - name: Run Live Installer
        shell: bash
        run: bash <(curl -sL https://csf.black.host)

      - name: Verify Configuration Exists
        run: |
          if [ -f "/etc/csf/csf.conf" ]; then
            echo "csf.conf found"
          else
            echo "csf.conf NOT found"
            exit 1
          fi

      - name: Verify Binary Exists
        run: |
          if [ -f "/usr/sbin/csf" ]; then
            echo "csf binary found"
          else
            echo "csf binary NOT found"
            exit 1
          fi

      - name: Check Version
        run: |
          if [ -f "/usr/local/csf/bin/csftest.pl" ]; then
             perl /usr/local/csf/bin/csftest.pl || true
          fi
          csf -v || true
